### ISSUE TITLE
Server queue

### ISSUE THREAD

**Issue by podrivo** [daemonforge/DayZ-UniveralApi#2]
Hello! More of a question and not an issue.

I'm interested in understanding how you get the queue number for a DayZ server.
In this file you extract the number from a `lqs` tag:
https://github.com/daemonforge/DayZ-UniveralApi/blob/54da691cae70f791191469e89557377779e71c87/DayZWebService/serverquery.js#L33

Is this accurate? DayZ servers add the queue number to this tag?

Thank you!
All the best!

**Comment by daemonforge** [comment]
Yeah its extracted from the tags from the steam query
```js
let keywords = state.raw.tags.split(','); // split it to array
let letQueueTag = keywords.find(tag => tag.includes('lqs')); // Find tag that has the lqs which is the queue
let actualQueue = parseInt(letQueueTag.replace('lqs', '')); // Remove the tag
```

**Comment by podrivo** [comment]
Wow! Thank you so much! This is huge! 🙌 

I was wondering, how did you find this?
I can't seem to find any documentation related.

And what else can we extract from tags?
I see you have:
```js
time: keywords.find(tag => tag.includes(':'))
first_person: keywords.some(tag => tag.includes('no3rd'))
time_acceleration: parseFloat((keywords.find(tag => tag.includes('etm')) || '12').replace('etm', '')) + ", " + parseFloat((keywords.find(tag => tag.includes('entm')) || '1').replace('entm', ''))
day_time_acceleration: parseFloat((keywords.find(tag => tag.includes('etm')) || '12').replace('etm', ''))
night_time_acceleration: parseFloat((keywords.find(tag => tag.includes('entm')) || '1').replace('entm', ''))
battleye: keywords.some(tag => tag.includes('battleye'))
public_hive: !keywords.some(tag => tag.includes('privHive'))
dlc_enabled: keywords.some(tag => tag.includes('isDLC'))
```

Thank you!

**Comment by daemonforge** [comment]
@podrivo I was shown this from Jad who made Magic Launcher You can just console log the Keywords and look through and change settings on the server though that's how I played with a bit more but couldn't think of much more to surface.

**Comment by podrivo** [comment]
Ohhh, I asked him the same thing: https://github.com/Jadfii/dayzmagiclauncher/issues/2
His API is in a private repo, so I wasn't able to understand how he got the queue number. Thankfully, I found yours! (:
