### ISSUE TITLE
Server mods

### ISSUE THREAD

**Issue by podrivo** [daemonforge/DayZ-UniveralApi#3]
Hey @daemonforge! Me again, with another question! 😄 
I'm interested in understanding more about how you link mods with a server and their Steam Workshop IDs.

I started exploring Valve server queries, using `gamedig` library. By requesting server rules, I got a response like this:

```
"rules": {
  "\u0001\n": "\u0001\u0001\u0001\u0002\u0001\u0002\u0001\u0002\"���\u0004\u0004]�k�\u0013Rearmed Server Packa�D�\u0004�\u0007��\u0010Rearmed Licensedʉ��\u0004�\u0013��\rCare Packages\u001bY��\u0004�{��\u0011Basic Territories�\u0001\u0001��\u0004�b\t�\u0013Re",
  "\u0002\n": "armed Helicopters\u0014�\"f\u0004�^L�\bCarCover=�\u0004_A��\u0013InventoryMoveSounds-\b!\u0016\u0004`��g\u000bSaline Bag+���\u0004P���\u0012Stranded-NVG-Fixes\u000f,\u001c�\u0004����\nWorn",
  "\u0003\n": "Repair���C\u0004�O�^\nTrader Mod0B\u001a\u0017\u0004�1\u0002�\u0016TraderFixesAndFeatures\u0005�g\u0006\u0004hM!z\nMuchCarKey�\u001c\u0002L\u0004�\u0014\u000b^\u0010Increased Lumensg<��\u0004��8m\rFlipTransport",
  "\u0004\n": "�p@�\u0004��sl\tEar Plugs\"ҝ�\u0004�Z�n\u0010BuildAnywhere_v3ڌ�l\u0004c0\u001e�\u0012ZT Vending Machine\u001a�\"�\u0004���\u0016Advanced Weapon Scopes�U��\u0004�8Bx\u000fzSpawnSelect",
  "\u0005\n": "ion`n�\u0006\u0004�>�e\nCPBWeapons�g�_\u0004\u000b_�j\u001d[Remastered] Arma Weapon Pack$�\u001e�\u0004\u0005~�l\u000fBreachingcharge\b\u0007:�\u0004��\u001eb\bCodeLock�ж\u0017\u0004\u0001\u0002\b'k\u0012WindstrideC",
  "\u0006\n": "lothing\u001f�}\u0004(��v\rMuchStuffPack�T��\u0004�p�e\u0010BaseBuildingPlus\n$XY\u0004�*e]\u0016Mass'sManyItemOverhaulÑ\u000e�\u0004A���\u0005FP IV�&e�\u0004�96a\u0015Cl0ud's Milita",
  "\u0007\n": "ry Gearo3\u0016�\u0004ƹ�e\rVPPAdminTools}�GS\u0004�MU]\fBuilderItems�\n\\\u0010\u0004\u0004��\\\u0013Community Framework����\u0013Ԓ\u0011\u000bLivonia DLC#\u000bA2Weaponsv3\u0003BBP\u0007BorizzK\u000b",
  "\b\n": "cftoolsRoot\u0007Cl0udV3\nCodeLockv3\u000bCooltrainV3\fCPBWeaponsV3\u000bdaemonforge\tDannyDoom\u0004dayz\ndayztrader\tdesignful\u0005FIDOv\u0004HDSN\tHelkhiana\u000bHe",
  "\t\n": "lkhianaV2\u0007Hunterz\fInclementDab\u0019Indi_Increased_Lumens_1.5\u0006Inkota\u000eJacob_Mango_V3\u0004Mass\fNotABananaV3\u000fNoVehicleDamage\u0012PattowieSSelec",
  "\n\n": "tion\u000eServerPanel_V3\bsimonvic\u0007sn0wLow\bViodugir\u0003VPP\tWardog.v3\nWindstride\u0012www.ZombieToast.de\u0005zysen"
}
```

This is the server I used: https://daemonforge.dev/Server/?ip=198.251.83.51&port=2405

But this response only gives me weird chars with the mod's names, but no Steam Workshop IDs.
I thought this could be a case of filtering this response and finding another method to link IDs, but I see you don't even request server rules with `gamedig`, but rather connect to an external MongoDB.

So I was wondering, how do you do this? What's the process to get these mod's info and link to a server?
Thank you!

**Comment by daemonforge** [comment]
@podrivo There is two ways most server have a mod server running due to DZSA requiring it it just +10 to the game port if you query it you'll get a json response with the mods the server is running
the second way is using buffers to read the data I got this working but its very hacky and can break completely if the mod doesn't have a mod.cpp file
You can see magic launchers method here.
https://github.com/Jadfii/dayzmagiclauncher/blob/release-2.0.0/src/main/query.js#L50

**Comment by podrivo** [comment]
Ohh, missed that file. Thanks for pointing it out! 🙌 

For the first way, are you talking about the ["Mod Download Server tool"](https://dayzsalauncher.com/#/tools) that DZSA has?

For the second way, can you explain a bit more about how this method could break if the mod doesn't have a mod.cpp file? I see mods have a `mod.cpp` and also a `meta.cpp` in their folder.

So I'm assuming, if the server doesn't have the DZSA tool and if one of the server mods doesn't have a mod.cpp file, players will need to use the official launcher. Is that the case?

Thank you!

**Comment by daemonforge** [comment]
@podrivo  Yes also Omega Manager also runs the mod server as well
http://192.95.50.50:2312/
you can see what it looks like with my API i use something similar to Magic Launcher but if it fails I try the Mod Query Port from Omega/DZSALauncher

**Comment by podrivo** [comment]
Omega Manager seems to be really good! And is it a free tool? Thanks for sharing!

This is perfect, @daemonforge! 
It's really hard to find documentation around this, so thank you so much for having the time! ✨

**Comment by daemonforge** [comment]
> Omega Manager seems to be really good! And is it a free tool? Thanks for sharing!
Yes it is free 
https://wiki.cftools.de/display/CFTOOL/OmegaManager

there is CF Cloud which has paid versions, but way worth it if you are serious about running a dayz server.

**Comment by podrivo** [comment]
Awesome! Feels like that it should be the default option for DayZ servers.

Thank you so much for sharing and for all the help! 🙌 ✨
